# Generated by Django 4.2.9 on 2025-11-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, help_text='Nombre personalizado del bot', max_length=200)),
                ('system_prompt', models.TextField(blank=True, help_text='Prompt del sistema para este bot específico')),
                ('specialty', models.TextField(blank=True, help_text='A qué se dedica la empresa')),
                ('tone', models.CharField(blank=True, help_text='Tono de comunicación del bot', max_length=255)),
                ('company_context', models.TextField(blank=True, help_text='Contexto detallado de la empresa')),
                ('industry_sector', models.CharField(blank=True, help_text='Sector industrial de la empresa', max_length=200)),
                ('services', models.JSONField(default=list, help_text='Lista de servicios')),
                ('language', models.CharField(choices=[('es-CO', 'Español Colombia'), ('es-MX', 'Español México'), ('es-ES', 'Español España'), ('en-US', 'English (US)')], default='es-CO', max_length=10)),
                ('additional_context', models.TextField(blank=True, help_text='Contexto adicional')),
                ('calendly_usage_description', models.TextField(blank=True, help_text='Descripción de cuándo el bot debe usar Calendly para agendar')),
                ('is_active', models.BooleanField(default=True)),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Indica si el onboarding se completó exitosamente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('system_prompt', models.TextField(help_text='Prompt base del sistema para este tipo de bot')),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono FontAwesome', max_length=50)),
                ('suggested_tone', models.CharField(blank=True, help_text='Tono sugerido', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, default='', help_text='Extensión del archivo', max_length=10)),
                ('minio_path', models.CharField(max_length=1000)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('chunks_created', models.IntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falla el procesamiento')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadatos del documento (páginas, tokens, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('bot_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bots.botconfig')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='botconfig',
            name='bot_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bot_configs', to='bots.bottype'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='accounts.company'),
        ),
    ]
