# Generated by Django 4.2.9 on 2025-10-01 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_id', models.IntegerField(unique=True)),
                ('specialty', models.TextField(help_text='A qué se dedica la empresa')),
                ('tone', models.CharField(help_text='Tono de comunicación', max_length=255)),
                ('services', models.JSONField(default=list, help_text='Lista de servicios')),
                ('language', models.CharField(choices=[('es-CO', 'Español Colombia'), ('es-MX', 'Español México'), ('es-ES', 'Español España'), ('en-US', 'English (US)')], default='es-CO', max_length=10)),
                ('additional_context', models.TextField(blank=True, help_text='Contexto adicional')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('minio_path', models.CharField(max_length=1000)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('chunks_created', models.IntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('bot_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bots.botconfig')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
