# Generated by Django 4.2.9 on 2025-10-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('system_prompt', models.TextField(help_text='Prompt base del sistema para este tipo de bot')),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono FontAwesome', max_length=50)),
                ('suggested_tone', models.CharField(blank=True, help_text='Tono sugerido', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='botconfig',
            name='bot_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bot_configs', to='bots.bottype'),
            preserve_default=False,
        ),
    ]
