# Generated by Django 4.2.9 on 2025-10-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bottype_botconfig_bot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Indica si el onboarding se completó exitosamente'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='bot_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bot_configs', to='bots.bottype'),
        ),
    ]
