# Generated by Django 4.2.9 on 2025-10-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_add_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Prompt del sistema para este bot específico'),
        ),
    ]
