# Generated by Django 4.2.9 on 2025-10-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_add_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='company_context',
            field=models.TextField(blank=True, help_text='Contexto detallado de la empresa'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='industry_sector',
            field=models.CharField(blank=True, help_text='Sector industrial de la empresa', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, help_text='Mensaje de error si falla el procesamiento'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(default=1, help_text='Extensión del archivo', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='specialty',
            field=models.TextField(blank=True, help_text='A qué se dedica la empresa'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='tone',
            field=models.CharField(blank=True, help_text='Tono de comunicación del bot', max_length=255),
        ),
    ]
