# Generated by Django 4.2.9 on 2025-10-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_botconfig_company_context_botconfig_industry_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, default='', help_text='Extensión del archivo', max_length=10),
        ),
    ]
