# Generated by Django 4.2.9 on 2025-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_document_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadatos del documento (páginas, tokens, etc.)'),
        ),
    ]
