# Generated by Django 4.2.9 on 2025-10-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_add_document_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre personalizado del bot', max_length=200),
        ),
    ]
