# Generated by Django 4.2.9 on 2025-10-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_botconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='calendly_usage_description',
            field=models.TextField(blank=True, help_text='Descripción de cuándo el bot debe usar Calendly para agendar'),
        ),
    ]
