# Generated by Django 4.2.9 on 2025-11-06 15:10

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('chatwoot_user_id', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts_activation_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('id_type', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('PP', 'Pasaporte'), ('CE', 'Cédula de Extranjería'), ('NUIP', 'NUIP')], max_length=10)),
                ('id_number', models.CharField(max_length=64)),
                ('id_dv', models.CharField(blank=True, max_length=8, null=True)),
                ('kind_of_person', models.CharField(choices=[('LEGAL_ENTITY', 'Persona Juridica'), ('PERSON_ENTITY', 'Persona Natural'), ('OTHER_ENTITY', 'Otra')], default='PERSON_ENTITY', max_length=20)),
                ('regime', models.CharField(blank=True, choices=[('COMMON_REGIME', 'Responsable de IVA'), ('SIMPLIFIED_REGIME', 'No responsable de IVA'), ('NATIONAL_CONSUMPTION_TAX', 'Impuesto Nacional al Consumo - INC'), ('NOT_REPONSIBLE_FOR_CONSUMPTION', 'No responsable de INC'), ('INC_IVA_RESPONSIBLE', 'Responsable de IVA e INC'), ('SPECIAL_REGIME', 'Régimen especial')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('admin_first_name', models.CharField(blank=True, max_length=150)),
                ('admin_last_name', models.CharField(blank=True, max_length=150)),
                ('admin_temp_password', models.CharField(blank=True, max_length=255)),
                ('chatwoot_account_id', models.IntegerField(blank=True, null=True)),
                ('chatwoot_access_token', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_provider', models.CharField(blank=True, default='calcom', max_length=50)),
                ('calendar_api_key', models.TextField(blank=True)),
                ('calendar_event_id', models.CharField(blank=True, max_length=50)),
                ('calendar_username', models.CharField(blank=True, max_length=255)),
                ('calendar_event_slug', models.CharField(blank=True, max_length=255)),
                ('calendar_booking_url', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Activo'), ('expired', 'Expirado'), ('converted', 'Convertido a pago'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('max_messages', models.IntegerField(default=1000)),
                ('max_conversations', models.IntegerField(default=100)),
                ('max_documents', models.IntegerField(default=10)),
                ('current_messages', models.IntegerField(default=0)),
                ('current_conversations', models.IntegerField(default=0)),
                ('current_documents', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='accounts.company')),
            ],
        ),
    ]
