# Generated by Django 4.2.9 on 2025-10-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20251002_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='activationtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
