# Generated by Django 4.2.9 on 2025-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_company_phone_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='admin_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
