# Generated by Django 4.2.9 on 2025-10-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_admin_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_temp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
