# Generated by Django 4.2.9 on 2025-10-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_temp_password_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='chatwoot_access_token',
            field=models.TextField(blank=True),
        ),
    ]
