# Generated by Django 4.2.9 on 2025-10-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_chatwoot_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('id_type', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('PP', 'Pasaporte'), ('CE', 'Cédula de Extranjería'), ('NUIP', 'NUIP')], max_length=10)),
                ('id_number', models.CharField(max_length=64)),
                ('id_dv', models.CharField(blank=True, max_length=8, null=True)),
                ('kind_of_person', models.CharField(choices=[('LEGAL_ENTITY', 'Legal Entity'), ('PERSON_ENTITY', 'Person'), ('OTHER_ENTITY', 'Other')], default='PERSON_ENTITY', max_length=20)),
                ('regime', models.CharField(blank=True, choices=[('COMMON_REGIME', 'Responsable de IVA'), ('SIMPLIFIED_REGIME', 'No responsable de IVA'), ('NATIONAL_CONSUMPTION_TAX', 'Impuesto Nacional al Consumo - INC'), ('NOT_REPONSIBLE_FOR_CONSUMPTION', 'No responsable de INC'), ('INC_IVA_RESPONSIBLE', 'Responsable de IVA e INC'), ('SPECIAL_REGIME', 'Régimen especial')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to='accounts.company')),
            ],
        ),
    ]
