# Generated by Django 4.2.9 on 2025-10-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_billinginfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinginfo',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='last_name',
        ),
    ]
