# Generated by Django 4.2.9 on 2025-10-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_remove_messages_storage_add_max_users'),
        ('accounts', '0011_rename_first_name_billinginfo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan asociado cuando el trial está ligado a un plan concreto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan'),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='kind_of_person',
            field=models.CharField(choices=[('LEGAL_ENTITY', 'Persona Juridica'), ('PERSON_ENTITY', 'Persona Natural'), ('OTHER_ENTITY', 'Otra')], default='PERSON_ENTITY', max_length=20),
        ),
    ]
