# Generated by Django 4.2.9 on 2025-10-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_trial_plan_alter_billinginfo_kind_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calendly_organization_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='calendly_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
