# Generated by Django 4.2.9 on 2025-10-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_company_calendly_organization_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calendly_user_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
