# Generated by Django 4.2.9 on 2025-10-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_company_calendly_user_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='calendly_organization_uri',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='calendly_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='calendly_user_uri',
            field=models.TextField(blank=True),
        ),
    ]
