# Generated by Django 4.2.9 on 2025-10-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_company_calendly_organization_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calendly_event_uri',
            field=models.TextField(blank=True),
        ),
    ]
