# Generated by Django 4.2.9 on 2025-10-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_company_calendly_event_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calendar_api_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='calendar_booking_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='calendar_event_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='calendar_provider',
            field=models.CharField(blank=True, default='calcom', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='calendar_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
