# Generated by Django 4.2.9 on 2025-10-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_company_calendar_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='calendly_event_uri',
        ),
        migrations.RemoveField(
            model_name='company',
            name='calendly_organization_uri',
        ),
        migrations.RemoveField(
            model_name='company',
            name='calendly_token',
        ),
        migrations.RemoveField(
            model_name='company',
            name='calendly_user_uri',
        ),
    ]
