# Generated by Django 4.2.9 on 2025-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_company_calendly_event_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
