# Generated by Django 4.2.9 on 2025-11-06 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Para porcentaje: 20.00 = 20%, Para fijo: monto en COP', max_digits=5)),
                ('apply_to_trial_expired', models.BooleanField(default=False, help_text='Aplicar cuando el trial haya expirado')),
                ('apply_to_new_users', models.BooleanField(default=False, help_text='Aplicar a usuarios nuevos')),
                ('minimum_plan_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio mínimo del plan para aplicar descuento', max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Máximo número de usos (opcional)', null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_inboxes', models.IntegerField(default=1)),
                ('max_documents', models.IntegerField(default=10)),
                ('max_users', models.IntegerField(default=3, help_text='Número máximo de usuarios/agentes permitidos')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Todas las características técnicas del plan (enviadas a Chatwoot API)')),
                ('summary_features', models.JSONField(blank=True, default=list, help_text="3-4 características destacadas para mostrar en tarjetas de planes. Formato: ['Feature 1', 'Feature 2', 'Feature 3']")),
                ('is_active', models.BooleanField(default=True)),
                ('trial_days', models.IntegerField(default=7)),
                ('wompi_plan_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Activa'), ('pending', 'Pago Pendiente'), ('suspended', 'Suspendida'), ('past_due', 'Pago Vencido'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('wompi_subscription_id', models.CharField(blank=True, max_length=255)),
                ('wompi_customer_email', models.EmailField(blank=True, max_length=254)),
                ('wompi_payment_method_id', models.CharField(blank=True, max_length=255)),
                ('payment_source_id', models.CharField(blank=True, help_text='ID de la fuente de pago para cobros automáticos', max_length=255)),
                ('card_brand', models.CharField(blank=True, help_text='Marca de la tarjeta (VISA, MASTERCARD, etc)', max_length=50)),
                ('card_last_four', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=4)),
                ('card_exp_month', models.CharField(blank=True, help_text='Mes de expiración', max_length=2)),
                ('card_exp_year', models.CharField(blank=True, help_text='Año de expiración', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wompi_reference', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('discount_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.discountcampaign')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('failed', 'Fallida'), ('voided', 'Anulada')], default='pending', max_length=20)),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('wompi_reference', models.CharField(blank=True, max_length=255)),
                ('invoice_pdf_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='ID único del evento de Wompi', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Tipo de evento (ej: transaction.updated)', max_length=50)),
                ('transaction_id', models.CharField(db_index=True, help_text='ID de la transacción en Wompi', max_length=255)),
                ('payload', models.JSONField(help_text='Payload completo del webhook')),
                ('signature', models.CharField(blank=True, help_text='Firma X-Event-Checksum recibida', max_length=255)),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido'), ('duplicate', 'Duplicado'), ('invalid_signature', 'Firma Inválida')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló el procesamiento')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se recibió el webhook')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Cuándo se terminó de procesar', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se recibió el webhook', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent del webhook', max_length=500)),
                ('invoice', models.ForeignKey(blank=True, help_text='Factura creada/actualizada por este webhook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='subscriptions.invoice')),
                ('subscription', models.ForeignKey(blank=True, help_text='Suscripción afectada por este webhook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_id'], name='subscriptio_event_i_6b830a_idx'), models.Index(fields=['transaction_id'], name='subscriptio_transac_282c26_idx'), models.Index(fields=['status'], name='subscriptio_status_669e13_idx'), models.Index(fields=['-received_at'], name='subscriptio_receive_f9cba9_idx')],
            },
        ),
    ]
