# Generated by Django 4.2.9 on 2025-10-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Para porcentaje: 20.00 = 20%, Para fijo: monto en COP', max_digits=5)),
                ('apply_to_trial_expired', models.BooleanField(default=False, help_text='Aplicar cuando el trial haya expirado')),
                ('apply_to_new_users', models.BooleanField(default=False, help_text='Aplicar a usuarios nuevos')),
                ('minimum_plan_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio mínimo del plan para aplicar descuento', max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Máximo número de usos (opcional)', null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
