# Generated by Django 4.2.9 on 2025-10-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_discountcampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Activa'), ('pending', 'Pago Pendiente'), ('past_due', 'Pago Vencido'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20),
        ),
    ]
