# Generated by Django 4.2.9 on 2025-10-07 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_temp_password_field'),
        ('subscriptions', '0003_alter_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wompi_reference', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('discount_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.discountcampaign')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan')),
            ],
        ),
    ]
