# Generated by Django 4.2.9 on 2025-10-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_pendingsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_source_id',
            field=models.CharField(blank=True, help_text='ID de la fuente de pago para cobros automáticos', max_length=255),
        ),
    ]
