# Generated by Django 4.2.9 on 2025-10-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_payment_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card_brand',
            field=models.CharField(blank=True, help_text='Marca de la tarjeta (VISA, MASTERCARD, etc)', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_exp_month',
            field=models.CharField(blank=True, help_text='Mes de expiración', max_length=2),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_exp_year',
            field=models.CharField(blank=True, help_text='Año de expiración', max_length=2),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=4),
        ),
    ]
