# Generated by Django 4.2.9 on 2025-10-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_add_card_info_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_messages_month',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_storage_mb',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='messages_used_this_month',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='storage_used_mb',
        ),
        migrations.AddField(
            model_name='plan',
            name='max_users',
            field=models.IntegerField(default=3, help_text='Número máximo de usuarios/agentes permitidos'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Activa'), ('pending', 'Pago Pendiente'), ('suspended', 'Suspendida'), ('past_due', 'Pago Vencido'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20),
        ),
    ]
