# Generated by Django 4.2.9 on 2025-11-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_remove_messages_storage_add_max_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='ID único del evento de Wompi', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Tipo de evento (ej: transaction.updated)', max_length=50)),
                ('transaction_id', models.CharField(db_index=True, help_text='ID de la transacción en Wompi', max_length=255)),
                ('payload', models.JSONField(help_text='Payload completo del webhook')),
                ('signature', models.CharField(blank=True, help_text='Firma X-Event-Checksum recibida', max_length=255)),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido'), ('duplicate', 'Duplicado'), ('invalid_signature', 'Firma Inválida')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló el procesamiento')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se recibió el webhook')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Cuándo se terminó de procesar', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se recibió el webhook', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent del webhook', max_length=500)),
                ('invoice', models.ForeignKey(blank=True, help_text='Factura creada/actualizada por este webhook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='subscriptions.invoice')),
                ('subscription', models.ForeignKey(blank=True, help_text='Suscripción afectada por este webhook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_id'], name='subscriptio_event_i_6b830a_idx'), models.Index(fields=['transaction_id'], name='subscriptio_transac_282c26_idx'), models.Index(fields=['status'], name='subscriptio_status_669e13_idx'), models.Index(fields=['-received_at'], name='subscriptio_receive_f9cba9_idx')],
            },
        ),
    ]
