# Generated by Django 4.2.9 on 2025-11-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='summary_features',
            field=models.JSONField(blank=True, default=list, help_text="3-4 características destacadas para mostrar en tarjetas de planes. Formato: ['Feature 1', 'Feature 2', 'Feature 3']"),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Todas las características técnicas del plan (enviadas a Chatwoot API)'),
        ),
    ]
