# Generated by Django 4.2.9 on 2025-11-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_plan_summary_features_alter_plan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_trial_plan',
            field=models.BooleanField(default=False, help_text='Marcar este plan como el plan base para períodos de prueba. Solo uno debe estar activo.'),
        ),
    ]
