# Generated by Django 4.2.9 on 2025-11-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSOToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Token SSO único generado con secrets.token_hex(32)', max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, default='', help_text='Email del usuario que será autenticado (opcional)', max_length=254)),
                ('chatwoot_account_id', models.CharField(help_text='ID de la cuenta de Chatwoot', max_length=50)),
                ('chatwoot_user_id', models.CharField(blank=True, help_text='ID del usuario en Chatwoot', max_length=50)),
                ('request_id', models.CharField(db_index=True, help_text='ID único de la solicitud para prevenir replay attacks', max_length=100, unique=True)),
                ('used', models.BooleanField(default=False, help_text='Indica si el token ya fue utilizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación del token')),
                ('expires_at', models.DateTimeField(help_text='Timestamp de expiración del token')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp cuando el token fue usado', null=True)),
            ],
            options={
                'verbose_name': 'SSO Token',
                'verbose_name_plural': 'SSO Tokens',
                'db_table': 'sso_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'used'], name='sso_token_used_idx'), models.Index(fields=['expires_at'], name='sso_expires_idx'), models.Index(fields=['request_id'], name='sso_request_idx')],
            },
        ),
    ]
