# Generated by Django 4.2.9 on 2025-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssotoken',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email del usuario que será autenticado (opcional)', max_length=254),
        ),
    ]
